export enum POIType{
    RESTAURANT = "restaurant",
    CLASS_ROOM = "class_room",
    PATIENT_ROOM = "patient_room",
    DOCTOR_ROOM = "doctor_room",
    YARD = "yard",
    BATHROOM = "bathroom",
    LAB = "lab",
    ROOM = "ROOM",
    ELEVATOR = "elevator",
    STAIRS = "stairs",
    ESCALATORS = "escalators",
    ROOM_ENTRANCE = "room_entrance",
    BUILDING_ENTRANCE = "building_entrance",
    EXIT = "exit",
    EMERGENCY_EXIT = "emergency_exit",    
    INFORMATION_DESK = "information_desk",
    UNKNOWN = "unknown",
    VENDING_MACHINE = "vending_machine",
    SMOKING_AREA = "smoking_area",
    CAFETERIA ="cafeteria",
}