# version: '3.8'

# services:
#   react-native:
#     image: reactnativecommunity/react-native-android
#     ports:
#       - "8081:8081"
#     volumes:
#       - ./Client:/app
#     devices:
#       - "/dev/bus/usb:/dev/bus/usb"  # Mount the USB devices for ADB
#     environment:
#       - ANDROID_HOME=/opt/android-sdk
#       - PATH=/opt/android-sdk/platform-tools:/opt/android-sdk/tools:$PATH
#     stdin_open: true
#     tty: true
version: '3.8'

services:
  reactnative:
    container_name: rnandroid
    build:
      context: .
      dockerfile: ./.docker/Dockerfile.android.rn
<<<<<<< Updated upstream
    # volumes:
    #   - ./Client:/app
      # - /dev/bus/usb:/dev/bus/usb  # Mount the USB devices for ADB
    # stdin_open: true
    # ports:
    #   - "5037:5037"
    #   - "8081:8081"
    # tty: true
    # privileged: true    
    environment:
      - ANDROID_ADB_SERVER_ADDRESS=host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: sh -c "cd /app && npm run android"
=======
    tty: true
    healthcheck:
      disable: true
    # privileged: true 
    # network_mode: host
    ports:
    - "5022:22"
    - "8081:8081"
    - "5901:5901"    
    # volumes:
    #   - ./:/Client/:delegated
    #   - notused:/./node_modules
    volumes:
      - /dev/bus/usb:/dev/bus/usb 
      - ~/.android:/root/.android  # Mount ADB keys into the container

    # entrypoint: [
    #   'bash', 
    #   '-c', 'adb connect localhost:8081 && npm run android']
    command: >
      sh -c "
      echo 'Starting Android application';
      adb connect localhost:8081;
      npm run android --verbose;
      sleep infinity;
      
      "
volumes:
  notused:
  
>>>>>>> Stashed changes
